theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  language: en
  palette:
    primary: 'pink'
    accent: 'pink'
  font:
    text: 'Lato'
    code: 'Ubuntu Mono'
  logo:
    icon: null
  feature:
    tabs: true
site_name: 'PinkDocs'
pages:
  - Intro: index.md
  - Block Chain: block-chain.md
  - Transactions: transactions.md
  - P2P Network: p2p.md
  - Pinkcoin API: api.md