site_name: 'PinkDocs' # Website name
docs_dir: 'src' # Markdown source file directory
site_dir: 'docs' # Destination for mkdocs build command

# Theme Options Required by Material theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  language: en
  palette:
    primary: 'pink'
    accent: 'pink'
  font:
    text: 'Lato'
    code: 'Ubuntu Mono'
  logo: 'img/PinkLogo.svg'
  feature:
    tabs: true

# Place Other Theme Options Below

# Page layout for navigation
# Markdown file must be listed here for Mkdocs to render/build
pages:
  - Introduction: index.md
  - Blockchain: block-chain.md
  - Transactions: transactions.md
  - P2P Network: p2p.md
  - Pinkcoin API: api.md